### ISSUE TITLE
Authentication and Data Binding

### ISSUE THREAD

**Issue by DanielMwendwa** [AfricasVoices/Operations-Dashboard#75]
Since every media and engagement dashboard page is using the same function to authenticate and bind data. We should create one function that accepts user and traffic name as parameters and returns data of the given traffic, then import the function on every file that it's needed.

**Comment by as2388** [comment]
Even better might be to have one traffic dashboard page which takes the project name as a query param. Then we can re-use everything :)

**Comment by DanielMwendwa** [comment]
Yeah. For now I'm just working on the architecture of how this can be implemented.

**Comment by as2388** [comment]
Let me know if you need pointers - there is a table in the database called 'active_projects' from which you should be able to pull all the necessary configuration required to do this.

**Comment by DanielMwendwa** [comment]
@as2388 please do so.

**Comment by as2388** [comment]
@DanielMwendwa the format for each active project definition is:
```
{
    "project_name": string,
    "operator_names": array of string,
    ...
}
```

These are stored in the Firestore at `/active_projects/<project_name>`

I think you can fetch all the documents from `/active_projects` to get the list of project names to populate the navbar dropdown with, and use the `operator_names` to populate the graph legends.

I think that's enough to implement the traffic dashboards as a single page, which doesn't need updating when we change projects because all the necessary configuration can be read from Firestore. If there's anything else you need though, let me know so we can think about how to add it.

**Comment by DanielMwendwa** [comment]
> @DanielMwendwa the format for each active project definition is:
> 
> ```
> {
>     "project_name": string,
>     "operator_names": array of string,
>     ...
> }
> ```
> 
> These are stored in the Firestore at `/active_projects/<project_name>`
> 
> I think you can fetch all the documents from `/active_projects` to get the list of project names to populate the navbar dropdown with, and use the `operator_names` to populate the graph legends.
> 
> I think that's enough to implement the traffic dashboards as a single page, which doesn't need updating when we change projects because all the necessary configuration can be read from Firestore. If there's anything else you need though, let me know so we can think about how to add it.

@as2388 worked on this issue: #122.
